project:
  type: book
  resources:
    - assets/figures/**/*.png

profile:
  default: public
  group:
    - [public, anonymous]

book:
  title: "Tracking Accessibility Over Time"
  subtitle: "A reproducible multimodal routing workflow"
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - 1-introduction.qmd
    - 2-data.qmd
    - 3-routing.qmd
    - 4-scaling.qmd
    - 5-casestudy.qmd
    - 6-conclusion.qmd

bibliography: references.bib
csl: sage-harvard.csl

format:
  html:
    theme: cosmo
    css: custom.css
    lightbox: true
    number-depth: 2

knitr:
  opts_chunk:
    eval: false

editor:
  render-on-save: true
